In [24]:
!pip install pandas

import pandas as pd

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [109]:
own_data = pd.read_csv('/work/IdaHeleneDencker#2808/Exam/Data/Own_data/combined.csv', index_col=0)
own_data

,win,loss,total_pr_trial,accumulated_score,deck_select,no,session,sub_ID,data_type,Study,Group
0,50,0,50,50,3,1,1,136,fmri,own,1
1,100,-250,-150,-100,1,2,1,136,fmri,own,1
2,50,0,50,-50,4,3,1,136,fmri,own,1
3,100,-250,-150,-200,1,4,1,136,fmri,own,1
4,100,0,100,-100,2,5,1,136,fmri,own,1
...,...,...,...,...,...,...,...,...,...,...,...
1915,50,-250,-200,1050,4,36,4,148,MEG,own,1
1916,50,0,50,1100,4,37,4,148,MEG,own,1
1917,50,0,50,1150,4,38,4,148,MEG,own,1
1918,50,0,50,1200,4,39,4,148,MEG,own,1
1919,50,0,50,1250,4,40,4,148,MEG,own,1

# Data from https://osf.io/8t7rm/

In [110]:
index = pd.read_csv('/work/IdaHeleneDencker#2808/Exam/Data/617_data/index_100.csv')
index

     Subj      Study
0       1  Horstmann
1       2  Horstmann
2       3  Horstmann
3       4  Horstmann
4       5  Horstmann
..    ...        ...
499   500     Worthy
500   501     Worthy
501   502     Worthy
502   503     Worthy
503   504     Worthy

[504 rows x 2 columns]

In [111]:
choice = pd.read_csv('/work/IdaHeleneDencker#2808/Exam/Data/617_data/choice_100.csv')
choice

choiceflip =choice.transpose()

choiceflip.reset_index(inplace=True)
choiceflip.rename(columns={'index': 'trial'}, inplace=True)

# Melt the DataFrame to get the desired format
reshaped_df_choice = choiceflip.melt(id_vars=['trial'], var_name='sub_ID', value_name='deck_select')

# Extract the numeric part of ID
reshaped_df_choice['sub_ID'] = reshaped_df_choice['sub_ID'].str.extract('(\d+)').astype(int)

# Extract the numeric part of trial
reshaped_df_choice['trial_Num'] = reshaped_df_choice['trial'].str.extract('(\d+)').astype(int)

# Sort by ID and numeric part of trial
reshaped_df_choice.sort_values(by=['sub_ID', 'trial_Num'], inplace=True)

# Drop the temporary 'trial_Num' column
reshaped_df_choice.drop(columns=['trial_Num'], inplace=True)

# Reset the index for cleaner output
reshaped_df_choice.reset_index(drop=True, inplace=True)

#rename
reshaped_df_choice = reshaped_df_choice.rename(columns={'trial': 'no'})

#cleaning no
reshaped_df_choice['no'] = reshaped_df_choice['no'].str.replace('Choice_', '', case=False, regex=True)


# Display the reshaped DataFrame
reshaped_df_choice

<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:16: SyntaxWarning: invalid escape sequence '\d'
<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:16: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_348/1096811427.py:13: SyntaxWarning: invalid escape sequence '\d'
  reshaped_df_choice['sub_ID'] = reshaped_df_choice['sub_ID'].str.extract('(\d+)').astype(int)
/tmp/ipykernel_348/1096811427.py:16: SyntaxWarning: invalid escape sequence '\d'
  reshaped_df_choice['trial_Num'] = reshaped_df_choice['trial'].str.extract('(\d+)').astype(int)

        no  sub_ID  deck_select
0        1       1            1
1        2       1            1
2        3       1            2
3        4       1            4
4        5       1            3
...    ...     ...          ...
50395   96     504            4
50396   97     504            2
50397   98     504            2
50398   99     504            2
50399  100     504            4

[50400 rows x 3 columns]

In [112]:
win = pd.read_csv('/work/IdaHeleneDencker#2808/Exam/Data/617_data/wi_100.csv')
win

winflip =win.transpose()

winflip.reset_index(inplace=True)
winflip.rename(columns={'index': 'trial'}, inplace=True)

# Melt the DataFrame to get the desired format
reshaped_df_win = winflip.melt(id_vars=['trial'], var_name='sub_ID', value_name='win')

# Extract the numeric part of ID
reshaped_df_win['sub_ID'] = reshaped_df_win['sub_ID'].str.extract('(\d+)').astype(int)

# Extract the numeric part of trial
reshaped_df_win['trial_Num'] = reshaped_df_win['trial'].str.extract('(\d+)').astype(int)

# Sort by ID and numeric part of trial
reshaped_df_win.sort_values(by=['sub_ID', 'trial_Num'], inplace=True)

# Drop the temporary 'trial_Num' column
reshaped_df_win.drop(columns=['trial_Num'], inplace=True) 

# Reset the index for cleaner output
reshaped_df_win.reset_index(drop=True, inplace=True)

#rename
reshaped_df_win = reshaped_df_win.rename(columns={'trial': 'no'})

#cleaning no
reshaped_df_win['no'] = reshaped_df_win['no'].str.replace('Wins_', '', case=False, regex=True)

# Display the reshaped DataFrame
reshaped_df_win

<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:16: SyntaxWarning: invalid escape sequence '\d'
<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:16: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_348/3087811338.py:13: SyntaxWarning: invalid escape sequence '\d'
  reshaped_df_win['sub_ID'] = reshaped_df_win['sub_ID'].str.extract('(\d+)').astype(int)
/tmp/ipykernel_348/3087811338.py:16: SyntaxWarning: invalid escape sequence '\d'
  reshaped_df_win['trial_Num'] = reshaped_df_win['trial'].str.extract('(\d+)').astype(int)

        no  sub_ID  win
0        1       1  100
1        2       1  100
2        3       1  100
3        4       1   50
4        5       1   50
...    ...     ...  ...
50395   96     504   50
50396   97     504  100
50397   98     504  100
50398   99     504  100
50399  100     504   50

[50400 rows x 3 columns]

In [113]:
loss = pd.read_csv('/work/IdaHeleneDencker#2808/Exam/Data/617_data/lo_100.csv')
loss

lossflip =loss.transpose()

lossflip.reset_index(inplace=True)
lossflip.rename(columns={'index': 'trial'}, inplace=True)

# Melt the DataFrame to get the desired format
reshaped_df_loss = lossflip.melt(id_vars=['trial'], var_name='sub_ID', value_name='loss')

# Extract the numeric part of ID
reshaped_df_loss['sub_ID'] = reshaped_df_loss['sub_ID'].str.extract('(\d+)').astype(int)

# Extract the numeric part of trial
reshaped_df_loss['trial_Num'] = reshaped_df_loss['trial'].str.extract('(\d+)').astype(int)

# Sort by ID and numeric part of trial
reshaped_df_loss.sort_values(by=['sub_ID', 'trial_Num'], inplace=True)

# Drop the temporary 'trial_Num' column
reshaped_df_loss.drop(columns=['trial_Num'], inplace=True) 

# Reset the index for cleaner output
reshaped_df_loss.reset_index(drop=True, inplace=True)

#rename
reshaped_df_loss = reshaped_df_loss.rename(columns={'trial': 'no'})

#cleaning no
reshaped_df_loss['no'] = reshaped_df_loss['no'].str.replace('Losses_', '', case=False, regex=True)

# Display the reshaped DataFrame
reshaped_df_loss

<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:16: SyntaxWarning: invalid escape sequence '\d'
<>:13: SyntaxWarning: invalid escape sequence '\d'
<>:16: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_348/815490286.py:13: SyntaxWarning: invalid escape sequence '\d'
  reshaped_df_loss['sub_ID'] = reshaped_df_loss['sub_ID'].str.extract('(\d+)').astype(int)
/tmp/ipykernel_348/815490286.py:16: SyntaxWarning: invalid escape sequence '\d'
  reshaped_df_loss['trial_Num'] = reshaped_df_loss['trial'].str.extract('(\d+)').astype(int)

        no  sub_ID  loss
0        1       1  -200
1        2       1  -150
2        3       1     0
3        4       1  -250
4        5       1     0
...    ...     ...   ...
50395   96     504     0
50396   97     504     0
50397   98     504     0
50398   99     504     0
50399  100     504     0

[50400 rows x 3 columns]

In [127]:
df_merged = pd.merge(reshaped_df_win, reshaped_df_loss, on=['no', 'sub_ID'])
df_merged_final = pd.merge(df_merged, reshaped_df_choice, on=['no', 'sub_ID'])


# Merge with index df
df_merged_final_2 = pd.merge(df_merged_final, index, left_on='sub_ID', right_on='Subj')

# Drop the redundant 'Subj' column if needed
df_merged_final_2.drop(columns='Subj', inplace=True)

#add columns
    # total_pr_trial
df_merged_final_2['total_pr_trial'] = df_merged_final_2['win'] + df_merged_final_2['loss']

    # accumulated_score
    # Function to calculate accumulated score for each group
def calculate_accumulated_score(group):
    # Initialize the first accumulated score as total_pr_trial + 2000
    group['accumulated_score'] = 0
    group.loc[group.index[0], 'accumulated_score'] = group['total_pr_trial'].iloc[0] + 2000
    
    # Calculate accumulated score for the rest of the rows
    for i in range(1, len(group)):
        group.loc[group.index[i], 'accumulated_score'] = (
            group['accumulated_score'].iloc[i - 1] + group['total_pr_trial'].iloc[i]
        )
    
    return group

# Group by 'sub_ID' and apply the function
df_merged_final_2 = df_merged_final_2.groupby('sub_ID', group_keys=False).apply(calculate_accumulated_score)


df_merged_final_2['data_type']= 'unknown'

df_merged_final_2['session']= 1
df_merged_final_2['Group']= 2

#rearrange
df_merged_final_2 = df_merged_final_2[['win', 'loss','total_pr_trial', 'accumulated_score', 'deck_select', 'no', 'session','sub_ID','data_type','Study','Group']]

#no as int64
df_merged_final_2['no'] = df_merged_final_2['no'].astype('int64')

#Drop studies i wont need
#those with payoff scheme 2, is most similar to out data: that is Horstmann (n=162), Steingroever (n=70)
#will use Steingroever
final= df_merged_final_2[df_merged_final_2['Study'] == 'SteingroverInPrep']

final.to_csv('/work/IdaHeleneDencker#2808/Exam/Data/617_data/Steingrover_data.csv')

/tmp/ipykernel_348/2471863736.py:31: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_merged_final_2 = df_merged_final_2.groupby('sub_ID', group_keys=False).apply(calculate_accumulated_score)